---
# YAML is case sensitive
# Use spaces, not tabs, for indentation

# Specify the API version to use for deployment resources
apiVersion: apps/v1 

# Define the type of Kubernetes resource being created, in this case, a Deployment
kind: Deployment 

# Metadata for the Deployment
metadata:
  name: sparta-test-app-deployment # Name of the Deployment

# Specification for the Deployment
spec:
  selector:
    matchLabels:
      app: sparta-test-app # Label to identify pods managed by this Deployment; must match the pod template labels

  # Define the number of pod replicas to create
  replicas: 3 

  # Template for the pods that the Deployment will manage
  template:
    metadata:
      labels:
        app: sparta-test-app # Label assigned to the pods, matching the selector above

    # Specification for the containers within the pod
    spec:   
      containers:
      - name: nodejs # Name of the container within the pod
        image: ihassan777/sparta-test-app:v1-no-db # Docker image for the container
        ports:
        - containerPort: 3000 # Port exposed by the container

        # Environment variables for the container
        env:
          - name: DB_HOST # Database host connection string
            value: mongodb://mongodb-service:27017/posts # MongoDB connection URI
          - name: DB_PORT # Database port
            value: "27017" # Port number as a string

        # Command to run when the container starts
        command: ["sh", "-c", "node /usr/src/app/seeds/seed.js && npm start"] 
        # Runs a script to seed the database, then starts the Node.js app
